In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("../deep-past-initiative-machine-translation/bibliography.csv")
data.head()

,pdf_name,title,author,author_place,journal,volume,year,pages
0,"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, ...",Kleine Mitteilungen,Guido Kryszat,Mainz,Archiv für Orientforschung,51,2005/2006,247–249
1,"(OCR) CDOG 8, 2008, pp. 109-124 - Dercksen, J....",The Assyrian Colony at Kanesh,Jan Gerrit Dercksen,Leiden,NaN,NaN,2008,NaN
2,"(OCR) JCS 59, 2007, pp. 93-106 - Larsen, Mogen...",Individual and Family in Old Assyrian Society,Mogens Trolle Larsen,Copenhagen,JCS,59,2007,93–95
3,27_arastirma_3-libre.pdf,Ege-Akdeniz Bölgesi Sualtı Araştırması 2008 Yı...,"Dr. Haydar Dönmez, Candaş Keskin, Necdet Çeliktaş",Ankara,Araştırma Sonuçları Toplantısı,3,2009,1–397
4,28_arastirma_3-libre.pdf,Kültür Varlıkları ve Müzeler Genel Müdürlüğü A...,"A. Naci TOY, Candaş KESKİN, Mustafa ÜÇGÜL, Fet...",İstanbul,Araştırma Sonuçları,3,2010,1–397

In [4]:
data = pd.read_csv("../deep-past-initiative-machine-translation/eBL_Dictionary.csv")
data.head()

      word                                         definition derived_from
0     -a I                           "my" (1 sg. pron. suff.)     cf. -ī I
1    -am I  "to me" (1 sg. dat. suff.) 2. vent. affix (cf....          NaN
2  -atti I                     (adv. endings) (cf. GAG §113l)          NaN
3    -iš I  "to; like" term.-adv. suffix on subst.s and ad...          NaN
4    -ka I       "you" (2 m. sg. acc. suff.) (cf. GAG p.258b)          NaN

In [5]:
data = pd.read_csv("../deep-past-initiative-machine-translation/OA_Lexicon_eBL.csv")
data.head()

,type,form,norm,lexeme,eBL,I_IV,A_D,Female(f),Alt_lex
0,word,áb ša-ra-ni,ab šarrānē,ab šarrānē,https://www.ebl.lmu.de/dictionary?word=ab šarrānē,NaN,NaN,NaN,NaN
1,word,áb ša-ra-nim,ab šarrānem,ab šarrānē,https://www.ebl.lmu.de/dictionary?word=ab šarrānē,NaN,NaN,NaN,NaN
2,word,áb-ša-ra-nim,ab šarrānem,ab šarrānē,https://www.ebl.lmu.de/dictionary?word=ab šarrānē,NaN,NaN,NaN,NaN
3,word,áb-ša-ra-ni,ab šarrānē,ab šarrānē,https://www.ebl.lmu.de/dictionary?word=ab šarrānē,NaN,NaN,NaN,NaN
4,word,áb-ša-ra-ni₇,ab šarrānē,ab šarrānē,https://www.ebl.lmu.de/dictionary?word=ab šarrānē,NaN,NaN,NaN,NaN

In [7]:
data = pd.read_csv("../deep-past-initiative-machine-translation/publications.csv")
data.head()

,pdf_name,page,page_text,has_akkadian
0,"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, ...",1,Kleine Mitteilungen\nAltassyrische Miszellen 2...,False
1,"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, ...",2,248\nKleine Mitteilungen\nKleine Mitteilungen\...,False
2,"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, ...",1,Kleine Mitteilungen\nAltassyrische Miszellen 2...,False
3,"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, ...",2,248\nKleine Mitteilungen\nKleine Mitteilungen\...,False
4,"(OCR) CDOG 8, 2008, pp. 109-124 - Dercksen, J....",1,THE AssYRIAN COLONY AT KANEsH\nJan Gerrit Derc...,False

In [8]:
data = pd.read_csv("../deep-past-initiative-machine-translation/published_texts.csv")
data.head()

,oare_id,online transcript,cdli_id,aliases,label,publication_catalog,description,genre_label,inventory_position,online_catalog,note,interlinear_commentary,online_information,excavation_no,oatp_key,eBL_id,AICC_translation,transliteration_orig,transliteration
0,bd4b7138-70d5-490d-8234-299b0a75d3a3,https://oare.byu.edu/epigraphies/bd4b7138-70d5...,P361099,MP 1 bis,Cuneiform Tablet RA 60 125,RA 60 125,"Cuneiform envelope, dated to the Old Assyrian ...",letter,MP 1 bis,NaN,Collection: MP 1 bis,"P. Garelli RA 60 S. 124-125; Michel Innaya II,...",NaN,NaN,4395,NaN,https://aicuneiform.com/search?q=P361099,KIŠIB a-šùr-ma-lik DUMU i-na-a a-na a-šùr-na-d...,KIŠIB a-šùr-ma-lik DUMU i-na-a a-na a-šùr-na-d...
1,b05376c2-fc3d-49f8-9792-a25c0df9c383,https://oare.byu.edu/epigraphies/b05376c2-fc3d...,P359543,ICK 1 146,Cuneiform Tablet ICK 1 146,Ka 185 | Ka 455 | Ka 424?,"Cuneiform tablet, dated to the Old Assyrian Pe...",debt note,Ist Ka 185 | Ist Ka 455 | Ist Ka 424?,NaN,"ICK 1, 146 & ICK 2, 33 (env) + ICK 2, 163 (env)","Ichisar, Imdilum 65f.",NaN,NaN,1888,NaN,https://aicuneiform.com/search?q=P359543,0.33333 ma-na 7 GÍN KÙ.BABBAR ṣa-ru-pá-am i-ṣé...,0.33333 ma-na 7 GÍN KÙ.BABBAR ṣa-ru-pá-am i-ṣé...
2,80547963-f2a2-4d5d-9544-fc7ada60d3b2,https://oare.byu.edu/epigraphies/80547963-f2a2...,P361681,TrMA 1 | Or 36 396 n. 2,Cuneiform Tablet Or 36 396A.2,NaN,"Cuneiform tablet, dated to the Old Assyrian Pe...",debt note,TrMA 1,NaN,Or 36 396 n. 2,NaN,NaN,NaN,56,NaN,https://aicuneiform.com/search?q=P361681,{large break} a-na a-lá-lá-ma-sí ù a-mur-DINGI...,<gap> a-na a-lá-lá-ma-sí ù a-mur-DINGIR qí-bi4...
3,8c0d4238-f795-4061-8b3c-8469a66d86d6,https://oare.byu.edu/epigraphies/8c0d4238-f795...,P361098,MP 1,Cuneiform Tablet RA 60 123,RA 60 123,"Cuneiform tablet, dated to the Old Assyrian Pe...",letter,MP 1,NaN,NaN,NaN,NaN,NaN,4394,NaN,https://aicuneiform.com/search?q=P361098,um-ma PUZUR₄-a-šùr-ma a-na bu-za-zu qí-bi-ma a...,um-ma PUZUR4-a-šùr-ma a-na bu-za-zu qí-bi-ma a...
4,2c0d870b-cd5e-fc36-8d81-114ecc7a9ac4,https://oare.byu.edu/epigraphies/2c0d870b-cd5e...,P290300,CCT 6 17a,Cuneiform Tablet CCT 6 17a (BM 115099),NaN,"Cuneiform tablet, dated to the Old Assyrian Pe...",unknown,BM 115099,NaN,"CCT 6, 17a","EL 320; 2-7: Garelli, AC 176A.4; 29-32: ebd. 3...",NaN,NaN,1603,NaN,https://aicuneiform.com/search?q=P290300,bu-za-zu il₅-we-da-ku iš-a-al-ma um-ma bu-za-z...,bu-za-zu il5-we-da-ku iš-a-al-ma um-ma bu-za-z...

In [14]:
import pandas as pd

# 读取原始 CSV
input_file = "../deep-past-initiative-machine-translation/publications.csv"
output_file = "publications.csv"

# 截取前 5000 行
df = pd.read_csv(input_file).head(1000)

# 保存到新的 CSV 文件
df.to_csv(output_file, index=False)

print(f"已保存前 1000 行到 {output_file}")

已保存前 1000 行到 publications.csv

In [12]:
data = pd.read_csv("../deep-past-initiative-machine-translation/train.csv")
data.head()

,oare_id,transliteration,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ..."
1,0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,Itūr-ilī has received one textile of ordinary ...
2,0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,<gap> he did not give you a textile. He return...
3,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-{d}EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū..."
4,00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta...,From Šukkutum to Ištar-lamassī and Nitahšušar:...

In [15]:
data = pd.read_csv("../deep-past-initiative-machine-translation/Sentences_Oare_FirstWord_LinNum.csv")
data.head()

,display_name,text_uuid,sentence_uuid,sentence_obj_in_text,translation,first_word_transcription,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
0,(Adana 237a) envelope,871e7671-e26b-4808-9acb-1c4a7e1ed2e6,f98879ad-d891-4602-8443-965baab6845d,3,Seal: trading station of Šalatiwar.,NaN,KIŠIB,1,5,1.0,1,1
1,(Adana 237s),09260971-37a9-4b91-aa30-ff59322598e5,e3444ecf-0276-4e5a-90cb-1e08e9d9f65e,3,From Imdī-ilum to Luzina and Puzur-Ištar:,NaN,um-ma,1,5,1.0,1,1
2,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,cb7f723d-6e52-454d-8ca2-50863cab81cb,10,"To the representatives Aššur-imittī, Imdī-ilum...",qibima,qí-bi₄-ma,8,11,3.0,1,1
3,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,5dc308e4-1033-4200-8b8b-6626d155539c,20,Ilī-uṣranni brings you 10 minas refined silver.,Ilī-uṣranni,ì-lí-uṣ-ra-ni,15,21,6.0,1,1
4,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,49ae0d28-4916-4744-b316-607432f9b091,23,Weigh it out to the one you recorded as my gua...,ana,a-na,17,25,8.0,1,1